title: 프로젝트 문서
description: 프로젝트의 완벽한 가이드
theme: just-the-docs

# 색상 스키마 설정
color_scheme: dark

# 검색 설정
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# 네비게이션 설정
aux_links:
  "GitHub":
    - "//github.com/your-repo"

# 푸터 설정
footer_content: "Copyright &copy; 2024 Your Project. Distributed by an <a href=\"https://github.com/your-repo/LICENSE\">MIT license.</a>"

# Back to top 링크
back_to_top: true
back_to_top_text: "맨 위로"

# 이미지 설정
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true 